version: "3.7"

services:
    # image project
    web:
        # image: wyveo/nginx-php-fpm:php81
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/nginx/sites:/etc/nginx/sites-available
        ports:
            - "9999:80" #http
            - "443:443" #https
        expose:
            - 9999
        depends_on:
            - redis
            - mysql
        networks:
            - laravel_boilerplate
        container_name: laravel_app

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel_boilerplate
        container_name: laravel_mysql

    # redis
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        networks:
            - laravel_boilerplate
        container_name: laravel_redis

networks:
    laravel_boilerplate:
        driver: bridge